sonar.host.url=http://sonar.cdp.it
sonar.login=6473868182e0be1983fb68ad492a1a1577f1ef0b

sonar.projectName=sispar-simulatore_ui
sonar.projectKey=sispar-simulatore_ui

sonar.sources=src

sonar.dynamicAnalysis=reuseReports
sonar.scm.provider=git
sonar.verbose=false

sonar.sourceEncoding=UTF-8
